version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
parameters:
  branch:
    type: string
    default: master
  app-name: 
    type: string
    default: tranquil-temple-40140
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git